[package]
name = "templateer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
egui = "0.22.0"
eframe = "0.22.0"
miette = "5.10"
reqwest = "0.11"
flexver-rs = "0.1.2"
futures = "0.3"
rfd = "0.12"
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["full"] }
xml_dom = "0.2.6"
ratatui = "0.23.0"
crossterm = "0.27.0"
tui-textarea = { version = "0.2.2", default-features = false, features = ["ratatui-crossterm"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
js-sys = "0.3.64"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.64"
features = [
    "Document",
    "DomParser",
    "Element",
    "HtmlCollection",
    "Node",
    "NodeList",
    "SupportedType",
    "console",
]
