name: Build native
on: [push, pull_request]
jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
